# Generated by Django 4.2.2 on 2023-06-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROL',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.IntegerField()),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.rol')),
            ],
        ),
    ]
