# Generated by Django 4.2.1 on 2023-07-01 14:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('tipo_dni', models.CharField(max_length=10)),
                ('numero_dni', models.IntegerField()),
                ('direccion', models.TextField(default='direccion', max_length=100)),
                ('telefono', models.IntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomsUsers',
                'db_table': 'CustomUser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Detalle_Ingreso',
                'verbose_name_plural': 'Detalles_de_Ingresos',
                'db_table': 'DetalleIngresos',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('idestados', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipodni', models.CharField(max_length=10)),
                ('numerodni', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ROL',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(default='detalle', max_length=20)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.AutoField(primary_key=True, serialize=False)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('serieComprobante', models.CharField(max_length=10)),
                ('numeroComprobante', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.AutoField(primary_key=True, serialize=False)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('serieComprobante', models.CharField(max_length=10)),
                ('numeroComprobante', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.proveedores')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idenvio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('direccion_envio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_seguimiento', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.orden')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'db_table': 'Envio',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.articulos')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.orden')),
            ],
            options={
                'verbose_name': 'Detalle_Venta',
                'verbose_name_plural': 'Detalles_Ventas',
                'db_table': 'DetallesVenta',
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='idcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.categoria'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idestados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.rol'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
