# Generated by Django 4.2.2 on 2023-06-13 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idarticulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detalleingreso',
            fields=[
                ('iddetalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('idestados', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipodni', models.CharField(max_length=10)),
                ('numerodni', models.IntegerField(max_length=10)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rol',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='apellido',
        ),
        migrations.AddField(
            model_name='rol',
            name='detalle',
            field=models.CharField(default='detalle', max_length=20),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='direccion',
            field=models.TextField(default='direccion', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='numero_dni',
            field=models.IntegerField(default=-2016, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(default=-2016, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_dni',
            field=models.CharField(default=-2016, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('serieComprobante', models.CharField(max_length=10)),
                ('numeroComprobante', models.IntegerField(default=0, max_length=1000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('serieComprobante', models.CharField(max_length=10)),
                ('numeroComprobante', models.IntegerField(default=0, max_length=1000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idenvio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('direccion_envio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_seguimiento', models.IntegerField(default=0, max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.estados')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='detalleVenta',
            fields=[
                ('iddetalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.articulo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.orden')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='idcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misapp.categoria'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idestados',
            field=models.ForeignKey(default=-2016, on_delete=django.db.models.deletion.CASCADE, to='misapp.estados'),
            preserve_default=False,
        ),
    ]
