# Generated by Django 4.2.1 on 2023-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.TextField(blank=True, default='direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numero_dni',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_dni',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
