# Generated by Django 4.2.2 on 2023-06-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misapp', '0002_articulo_categoria_detalleingreso_estados_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulo',
            new_name='Articulos',
        ),
    ]
