# Generated by Django 4.2.2 on 2023-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misapp', '0003_rename_articulo_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='idarticulo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idcategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalleingreso',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleingreso',
            name='iddetalle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='iddetalle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='envio',
            name='cod_seguimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='envio',
            name='idenvio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='idingreso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='numeroComprobante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idorden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='numeroComprobante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='idproveedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='numerodni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero_dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
