# Generated by Django 4.2.3 on 2023-07-10 16:52

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('dni', models.CharField(help_text='Maximo 8 caracteres', max_length=8, null=True)),
                ('fecha_nac', models.DateField(null=True)),
                ('telefono', models.CharField(help_text='Maximo 12 caracteres', max_length=12, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('tipo_presentacion', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('descripcion', models.CharField(help_text='Maximo 1000 caracteres', max_length=1000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.PositiveSmallIntegerField()),
                ('img_url', models.URLField(default='https://www.bayertecuida.es/sites/g/files/vrxlpx43471/files/2020-07/aspirina500mg-comprimidos_0.jpg')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, db_comment='The field is only automatically updated when calling Model.save()')),
            ],
            options={
                'verbose_name': 'Id del Carrito',
                'verbose_name_plural': 'Ids de los Carritos',
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del la categoria', max_length=100)),
                ('detalle', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('calle', models.CharField(help_text='Calle', max_length=100)),
                ('numero', models.CharField(help_text='Numero', max_length=100)),
                ('departamento', models.CharField(help_text='Ingrese numero departamento', max_length=10)),
                ('piso', models.CharField(help_text='Ingrese el piso', max_length=10)),
                ('barrio', models.CharField(help_text='Ingrese el barrio donde vive', max_length=100)),
            ],
            options={
                'verbose_name': 'Detalle Direccion',
                'verbose_name_plural': 'Detalles de Direcciones',
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(choices=[('1', 'Activo'), ('2', 'Desactivo'), ('3', 'Pendiente'), ('4', 'Aprobado'), ('5', 'Desaprobado'), ('6', 'En Proceso')], default='1', max_length=2)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Maximo 100 caracteres', max_length=100)),
                ('codigo_postal', models.CharField(help_text='Codigo postal', max_length=8)),
            ],
            options={
                'verbose_name': 'Nombre de Localidad',
                'verbose_name_plural': 'Nombres de Localidades',
                'db_table': 'Localidad',
            },
        ),
        migrations.CreateModel(
            name='ModoPago',
            fields=[
                ('id_mp', models.AutoField(primary_key=True, serialize=False)),
                ('tipos', models.CharField(choices=[('EF', 'Efectivo'), ('TF', 'Transferencia'), ('TJ', 'Tarjeta'), ('DP', 'Deposito'), ("<enum 'Electronico'>", 'Electronico'), ('<django.db.models.fields.CharField>', 'Pagoeletronico')], default='EF', max_length=100)),
                ('detalle', models.TextField(blank=True, help_text='Detalle', max_length=200)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, max_length=99999)),
            ],
            options={
                'verbose_name': 'Modo de pago',
                'verbose_name_plural': 'Modos de pagos',
                'db_table': 'modoPago',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('tipo_comprobante', models.CharField(help_text='tipo comprobante', max_length=20)),
                ('detalle_comprobante', models.CharField(help_text='Numero de Comprobante', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, max_length=99999)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modopago')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(choices=[('BA', 'Buenos Aires'), ('CT', 'Catamarca'), ('CH', 'Chaco'), ('CB', 'Chubut'), ('CD', 'Cordoba'), ('CR', 'Corrientes'), ('ER', 'Entre Rios'), ('FO', 'Formosa'), ('JY', 'Jujuy'), ('LP', 'La Pampa'), ('LR', 'La Rioja'), ('MZ', 'Mendoza'), ('MN', 'Misiones'), ('NQ', 'Neuquen'), ('RN', 'Rio Negro'), ('SA', 'Salta'), ('SJ', 'San Juan'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SE', 'Santiago Del Estero'), ('TF', 'Tierra Del Fuego'), ('TM', 'Tucuman')], default='BA', max_length=2)),
            ],
            options={
                'verbose_name': 'Nombre de Provincia',
                'verbose_name_plural': 'Nombres de Provincias',
                'db_table': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('seguimiento', models.CharField(choices=[('CC', 'En Camino'), ('AA', 'Armando Pedido'), ('EE', 'Entregado'), ('DV', 'Devolucion')], default='AA', max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_comment='The field is only automatically updated when calling Model.save()')),
                ('nro_tracking', models.CharField(help_text='Maximo 40 caracteres', max_length=40)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orden')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pagos', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, db_comment='The field is only automatically updated when calling Model.save()')),
                ('code', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('dni', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('email', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('tarjeta', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('titular', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('vencimiento', models.CharField(help_text='Maximo 200 caracteres', max_length=200)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Datos generales de Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, help_text='Ingrese el valor del envio', max_digits=10, max_length=10)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direccion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'db_table': 'Envio',
            },
        ),
        migrations.CreateModel(
            name='ElementosCarrito',
            fields=[
                ('id_elementos_carrito', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articulo')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrito')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento del Carrito',
                'verbose_name_plural': 'Elementos de los Carritos',
                'db_table': 'elementos_carrito',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localidad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articulo')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
            options={
                'verbose_name': 'Detalle del Pedido',
                'verbose_name_plural': 'Detalles de los Pedidos',
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser', to='app.carrito'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.direccion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
